project:
  type: website

website:
  title: "Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: pages/profil.qmd
        text: Profil
      - href: pages/articles.qmd
        text: Articles
      - href: pages/projets.qmd
        text: Projets
      - href: pages/tidytuesday.qmd
        text: Tidytuesday
    right:
      - icon: github
        href: https://github.com/fmarchais
      - icon: linkedin
        href: www.linkedin.com/in/f√©lix-marchais
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: source